kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace }}
  name: rabbitmq
  labels:
    app: {{ .Values.prefix }}
    type: LoadBalancer
spec:
  type: ClusterIP
  ports:
   - name: http
     port: 15672
   - name: amqp
     port: 5672
  selector:
    app: {{ .Values.prefix }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-rmq-mgmt
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.prefix }}-rmq-mgmt
spec:
  type: ClusterIP
  ports:
    - name: rmqmgmt
      port: 15672
  selector:
    name: {{ .Values.prefix }}-web-deploy
