apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-web-svc
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.prefix }}-web-svc
spec:
  type: ClusterIP
  externalIPs:
    - 172.31.209.176
  ports:
    - name: http
      # port: 80
      port: 32371
      targetPort: 8052
  selector:
    name: {{ .Values.prefix }}-web-deploy
