apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: pv-postgres
          hostPath:
            path: /data/awx/pv-postgres
            type: DirectoryOrCreate
      containers:
        - name: postgres
          image: postgres:11.6-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pv-postgres
              subPath: pgdata
          env:
            - name: POSTGRES_USER
              value: {{ .Values.pg_username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.pg_password }}
            - name: POSTGRES_DB
              value: {{ .Values.pg_database }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pg_hostname }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - port: 5432
