---
- name: Build AWX Docker Images
  hosts: all
  gather_facts: false
  roles:
    - {role: image_build}
    - {role: image_push, when: "docker_registry is defined"}



# todo 确保这两个库安装好
# pip3 install requests docker
